### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by obsoleted** [arduino-libraries/AzureIoTHub#15]
Can we get a new version of the library published with the latest changes?

**Comment by sandeepmistry** [comment]
I think we need to resolve #14 and #6 before publishing a new version.

Also, the documentation needs to be updated, some of the examples require some additional libraries for sensors that are not mentioned in the read me currently.

**Comment by sandeepmistry** [comment]
Ok, we are getting closer!

So, now we need to:
 * update some documentation
 * wait for a 3.0.0 release of  NTPClient (https://github.com/arduino-libraries/NTPClient/issues/9)
 * maybe tackle #17

**Comment by sandeepmistry** [comment]
@obsoleted could you please review #13 and #18 (and merge if they look good).

Then we should be good to go for a new release.

**Comment by sandeepmistry** [comment]
@obsoleted are there any other changes you'd like before we release a new version? Do you have any preferences on the version number?

Let's aim to tag a new release early next week.

**Comment by obsoleted** [comment]
I think 0.2.0 is fine for this release. I don't think any other changes are needed at this time.

**Comment by sandeepmistry** [comment]
Ok, I'll do a basic test on the MKR1000 and WiFi101 on Monday morning (ET). Then tag a 0.2.0 release in the afternoon after renaming the repo to ```AzureIoTHub```

**Comment by obsoleted** [comment]
Cool. I'll probably have ran through the ESP8266s i have and the feather m0 wifi by then also.

**Comment by stefangordon** [comment]
Thanks Sandeep, getting this out soon will be a big help as there are hundreds of folks trying to use it already and some confusion about the version in the IDE vs. in the repo.  0.2.0 sounds good to me also.

**Comment by sandeepmistry** [comment]
`simplesample_http` looks good on both the MKR1000 and Zero + WiFi101.

Let me know when you're ready for me to tag the v0.2.0 release and rename the repo. I'll also be renaming the existing 0.0.0 and 0.1.0 tags so they aren't installable via the library manager. This is to avoid `AzureIot` and `AzureIoTHub` being listed in the library manager, we only want the latter to avoid confusion.

**Comment by stefangordon** [comment]
Great! Go ahead and release at your convenience - I will keep an eye on it and update all our various documentation as appropriate.

**Comment by sandeepmistry** [comment]
v0.2.0 is out! One note, I ended up deleting the v0.0.0 and v0.1.0 tags to prevent `AzureIoT` from being present in the library manager.

@stefangordon great, could you please also look at #10.
